In [2]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from fixDtypeWarning import getColumns
from fixDtypeWarning import makeTypeDict
# Read data
DATA_FOLDER= "./data/"
stackoverflowData = DATA_FOLDER + "raw/stackoverflowPost.csv"
typeColumns = DATA_FOLDER + "typeColumList.csv"
keysList = getColumns(stackoverflowData)
valueList = getColumns(typeColumns)
dtypeDict = makeTypeDict(keysList , valueList)

In [17]:
def dataInfo(dataset):
    info = pd.read_csv(dataset, dtype=dtypeDict)
    return info.shape
dataInfo(stackoverflowData)#.memory_usage().sum()

(100000, 21)

In [5]:
def toDatetime(dataset, columns):
    return

In [20]:
def dataPipiline(dataset):
    df = (
        pd.read_csv(dataset, dtype=dtypeDict)
        .rename(columns=str.lower)
        .drop(['unnamed: 0' , 'parent_id' , 'community_owned_date'], axis=1)
        .assign(
            last_activity_date = lambda x: pd.to_datetime(x['last_activity_date']),
            last_edit_date = lambda x: pd.to_datetime(x['last_activity_date']),
                )
        )
    return df


dataPipiline(stackoverflowData).sample(frac=0.50, replace=False, random_state=45)

,id,title,body,accepted_answer_id,answer_count,comment_count,creation_date,favorite_count,last_activity_date,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,post_type_id,score,tags,view_count
57250,65788018,Like to make api call once and use data in all...,<p>Tried creating a singleton type component b...,65788174,2,0,2021-01-19 08:46:26.450000+00:00,<NA>,2021-01-19 08:56:52.433000+00:00,2021-01-19 08:56:52.433000+00:00,NaN,128165,NaN,13893142,1,-1,json|reactjs|api,28
34573,68924673,"Unable to install msi file. Getting error ""Win...",<p>I'm trying to install mongoDb on windows 8....,<NA>,1,0,2021-08-25 14:21:59.943000+00:00,<NA>,2021-08-31 07:09:30.943000+00:00,2021-08-31 07:09:30.943000+00:00,NaN,<NA>,NaN,6618669,1,0,mongodb|installation|permissions|windows-8.1|a...,14
15532,64477028,how to iterate over files in python and export...,<p>I have a code and I want to put it in a for...,64477331,1,0,2020-10-22 07:10:40.143000+00:00,<NA>,2020-10-22 07:31:43.887000+00:00,2020-10-22 07:31:43.887000+00:00,NaN,<NA>,NaN,14125436,1,0,python|arrays|numpy|file,29
58088,65710343,popover functionality lost once another popove...,<p>I have multiple popovers on a page. some ha...,<NA>,1,0,2021-01-13 21:54:12.290000+00:00,<NA>,2021-01-19 12:41:27.813000+00:00,2021-01-19 12:41:27.813000+00:00,NaN,<NA>,NaN,11090374,1,0,angularjs|popover,29
40218,68812744,Spring data jpa id make unsigne?,<p>I Use Entity like that.</p>\n<pre><code> @...,<NA>,0,0,2021-08-17 06:44:58.800000+00:00,<NA>,2021-08-26 01:17:39.277000+00:00,2021-08-26 01:17:39.277000+00:00,NaN,3066285,NaN,3066285,1,0,jpa|spring-data-jpa,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35178,69015758,(Vue.js) Capacitor mobile app background procc...,<p>So I'm writing an app in <strong>Vue.js</st...,<NA>,0,0,2021-09-01 14:31:53.307000+00:00,<NA>,2021-09-02 07:03:07.230000+00:00,2021-09-02 07:03:07.230000+00:00,NaN,10195153,NaN,9925625,1,0,vue.js|rabbitmq|service-worker|background-proc...,14
53823,65603319,Types accepted as parameters for scikit-learn....,<p>I am working on a project where I am using ...,65603341,1,0,2021-01-06 21:02:41.857000+00:00,<NA>,2021-01-06 21:04:45.453000+00:00,2021-01-06 21:04:45.453000+00:00,NaN,<NA>,NaN,8452867,1,1,python|arrays|pandas|machine-learning|scikit-l...,25
98367,15384791,count rows using three tables,<p>I've three mysql database tables as </p>\n\...,<NA>,1,0,2013-03-13 12:02:37.810000+00:00,<NA>,2013-03-13 12:50:31.147000+00:00,2013-03-13 12:50:31.147000+00:00,NaN,426671,NaN,1711072,1,0,mysql|join,63
27782,68791131,How to install TDengine database on Mac OS,"<p>I follow the step from this link <a href=""h...",68797205,1,0,2021-08-15 11:36:09.363000+00:00,<NA>,2021-08-16 03:47:21.923000+00:00,2021-08-16 03:47:21.923000+00:00,NaN,<NA>,NaN,16492986,1,0,td-engine,11
71085,59758069,Convert Amount to Words in Crystal Report,"<p>I am working on a crystal report, can someo...",<NA>,1,0,2020-01-15 19:06:52.947000+00:00,<NA>,2020-01-15 23:16:29.397000+00:00,2020-01-15 23:16:29.397000+00:00,NaN,<NA>,NaN,12293892,1,-1,crystal-reports,37

In [2]:
def readData(dataset):
    df = (
        pd.read_csv(dataset)
        .rename(columns=str.lower)
        .drop(['unnamed: 0' , 'parent_id'], axis=1)
        .pipe(newTagsColumn)
        .assign(
            community_owned_date = lambda x: pd.to_datetime(x['community_owned_date']),
            last_activity_date = lambda x: pd.to_datetime(x['last_activity_date']),
            last_edit_date = lambda x: pd.to_datetime(x['last_activity_date']),
            post_type_id = lambda x: x['post_type_id'].astype('category'),
            creation_date = lambda x: pd.to_datetime(x['creation_date']),
            id = lambda x: x['id'].astype('category'),
            last_editor_user_id = lambda x: 
                                x['last_editor_user_id']
                                .fillna('not id')
                                .astype('category'),
            accepted_answer_id = lambda x: 
                                x['accepted_answer_id']
                                .fillna('not id')
                                .astype('category'),
            favorite_count = lambda x: 
                            x['favorite_count']
                            .fillna(10.0)
                            .astype(np.int8),                         
            owner_user_id = lambda x: 
                            x['owner_user_id']
                            .fillna('not id')
                            .astype('category')
        )
        
    )
    return (df
        .astype({
        'comment_count' : np.int8,
        'answer_count' : np.int8,
        'view_count' : np.int16,
        'score' : np.int8,
        }
        ))

def newTagsColumn(dataframe):
    return (
        dataframe
        .assign(
            tags = dataframe['tags']
            .loc
            [dataframe['tags']
            .isin(
                dataframe['tags']
                .value_counts(dropna=False)
                .head(50)
                .index
                .to_list()
                )
            ],
            new_tags = (lambda x
                    : x['tags']
                    .fillna('other')
                    .astype('category'))
        )
    )


stackData = readData(DATA_FOLDER_PATH + 'stackoverflow_data.csv')
stackData.head()

,id,title,body,accepted_answer_id,answer_count,comment_count,community_owned_date,creation_date,favorite_count,last_activity_date,last_edit_date,last_editor_display_name,last_editor_user_id,owner_display_name,owner_user_id,post_type_id,score,tags,view_count,new_tags
0,14956161,Rspec tests fails after will_paginate-bootstra...,<p>I installed <code>will_paginate-bootstrap</...,not id,2,0,NaT,2013-02-19 11:18:48.757000+00:00,10,2013-02-19 12:37:21.840000+00:00,2013-02-19 12:37:21.840000+00:00,NaN,not id,NaN,83938.0,1,0,NaN,256,other
1,14957972,Duplicate ajax content,<p>I have a problem with duplicates ajax conte...,not id,1,5,NaT,2013-02-19 12:51:21.987000+00:00,10,2013-09-22 06:17:15.633000+00:00,2013-09-22 06:17:15.633000+00:00,NaN,1449059.0,NaN,2051017.0,1,0,NaN,256,other
2,14965880,Usefulness of Covering indexes,<p>I have a query that performs joins on multi...,14966007.0,2,0,NaT,2013-02-19 19:35:04.950000+00:00,10,2013-02-19 20:00:08.953000+00:00,2013-02-19 20:00:08.953000+00:00,NaN,643483.0,NaN,316419.0,1,0,NaN,256,other
3,14966051,partial matching no vba,"<p>Looking for a excel formula, that will part...",not id,3,1,NaT,2013-02-19 19:45:56.777000+00:00,10,2013-10-24 05:58:50.670000+00:00,2013-10-24 05:58:50.670000+00:00,NaN,2088509.0,NaN,2088509.0,1,0,NaN,256,other
4,14967045,Rotation over time in 3D,"<p>Im working with Xna 4, doing a game where i...",15091871.0,3,1,NaT,2013-02-19 20:45:24.820000+00:00,1,2013-02-26 16:41:41.947000+00:00,2013-02-26 16:41:41.947000+00:00,NaN,447156.0,NaN,1740413.0,1,0,NaN,256,other